In [9]:
import numpy as np
import pandas as pd
import wget

ModuleNotFoundError: No module named 'numpy'

In [7]:
pd.__version__

'2.3.2'

In [10]:
fn = wget.download('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [11]:
fn

'car_fuel_efficiency (1).csv'

In [8]:
df = pd.read_csv(fn)

NameError: name 'pd' is not defined

In [49]:
df

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                     170            3.0       159.0     3413.433759   
1                     130            5.0        97.0     3149.664934   
2                     170            NaN        78.0     3079.038997   
3                     220            4.0         NaN     2542.392402   
4                     210            1.0       140.0     3460.870990   
...                   ...            ...         ...             ...   
9699                  140            5.0       164.0     2981.107371   
9700                  180            NaN       154.0     2439.525729   
9701                  220            2.0       138.0     2583.471318   
9702                  230            4.0       177.0     2905.527390   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year  origin fuel_type         drivetrain  \
0             17.7        2003  Europe  Gasoline    All-wheel drive   
1             17.8        2007     USA  Gasoline  Front-wheel drive   
2             15.1        2018  Europe  Gasoline  Front-wheel drive   
3             20.2        2009     USA    Diesel    All-wheel drive   
4             14.4        2009  Europe  Gasoline    All-wheel drive   
...            ...         ...     ...       ...                ...   
9699          17.3        2013  Europe    Diesel  Front-wheel drive   
9700          15.0        2004     USA  Gasoline    All-wheel drive   
9701          15.1        2008     USA    Diesel    All-wheel drive   
9702          19.4        2011     USA    Diesel  Front-wheel drive   
9703          14.7        2005    Asia    Diesel    All-wheel drive   

      num_doors  fuel_efficiency_mpg  
0           0.0            13.231729  
1           0.0            13.688217  
2           0.0            14.246341  
3           2.0            16.912736  
4           2.0            12.488369  
...         ...                  ...  
9699        NaN            15.101802  
9700        0.0            17.962326  
9701       -1.0            17.186587  
9702        1.0            15.331551  
9703       -1.0            14.884467  

[9704 rows x 11 columns]

In [51]:
df.shape

(9704, 11)

In [56]:
df['fuel_type'].unique().size

2

In [83]:
df.isnull().sum()

engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64

In [64]:
df.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64

In [71]:
median_old = df.horsepower.median()

In [93]:
mode = df.horsepower.mode()
mode
type(mode)
mode = int(mode)
mode

C:\Users\matte\AppData\Local\Temp\ipykernel_2948\3561727821.py:4: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  mode = int(mode)


152

In [89]:
df['horsepower'] = df['horsepower'].fillna(152)

In [94]:
df.horsepower

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [98]:
median_new = df.horsepower.median()

In [100]:
median_new

np.float64(152.0)

In [102]:
median_old

np.float64(149.0)

In [118]:
df = df[
    df['origin'] == 'Asia'
]

In [120]:
df = df[['vehicle_weight', 'model_year']]

In [122]:
df

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

In [159]:
x = df.head(7)
x

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

In [160]:
X = x.values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [164]:
XT = X.T
XTX = X.dot(XT)
XTX

array([[11431242.46085133, 11608190.92541486, 13770311.23387465,
        10111792.75336224, 11282536.19632532, 11780081.29349753,
        14281180.86123177],
       [11608190.92541486, 11790026.46575708, 14007802.20739725,
        10255171.44187306, 11455668.70489329, 11966096.78727446,
        14531088.48421337],
       [13770311.23387465, 14007802.20739725, 16863697.77478558,
        12031947.83608462, 13574023.463935  , 14232076.05656009,
        17530181.51805091],
       [10111792.75336224, 10255171.44187306, 12031947.83608462,
         9025088.58092514,  9989516.7638366 , 10397924.16669749,
        12456257.9230991 ],
       [11282536.19632532, 11455668.70489329, 13574023.463935  ,
         9989516.7638366 , 11136831.64128077, 11624252.15672766,
        14075069.26273247],
       [11780081.29349753, 11966096.78727446, 14232076.05656009,
        10397924.16669749, 11624252.15672766, 12145826.2645139 ,
        14766233.02574041],
       [14281180.86123177, 14531088.48421337, 175301

In [166]:
XTX_1 = np.linalg.inv(XTX)
XTX_1

array([[ 6.27784782e+08,  4.52348582e+08, -5.52589667e+08,
        -5.04518657e+08, -1.36497506e+08, -9.70745174e+07,
         2.07769569e+08],
       [ 6.52427761e+08,  1.18496810e+09, -8.15933475e+08,
        -7.54720098e+08, -7.08834488e+08,  2.53306835e+08,
         1.86771033e+08],
       [-4.82034184e+08, -5.85397198e+08,  3.79915957e+08,
         6.66310906e+08,  1.18051009e+08, -1.47095872e+08,
         5.16329750e+07],
       [-4.86725764e+08, -5.86851309e+08,  7.06448581e+08,
         6.82137781e+08,  2.06347119e+08, -3.29606193e+08,
        -1.88697388e+08],
       [-2.37576087e+08, -7.37561522e+08,  2.26902495e+08,
         2.89910408e+08,  1.50145296e+08,  3.48995157e+08,
        -4.08718420e+07],
       [-2.28618838e+08,  1.97697960e+08, -2.05812130e+07,
        -2.25519129e+08,  3.60824331e+08, -2.92220029e+06,
        -8.08263491e+07],
       [ 1.52870693e+08,  7.43387198e+07,  7.67225188e+07,
        -1.51179749e+08,  9.23761238e+06, -2.62872552e+07,
        -1.3533841

In [140]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [176]:
w = XT.dot(XTX_1).dot(y)
w

array([ 0.71258545, -0.23193359])

In [177]:
w.sum()

np.float64(0.48065185546875)